In [22]:
import tensorflow as tf
import numpy as np

In [23]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [24]:
# make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data,)

(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]


In [25]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [26]:
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [27]:
hypothesis = tf.matmul(X, W) + b

In [28]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [29]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [30]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [31]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train],
        feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  10703.978 
Prediction:
 [[60.866592]
 [64.36042 ]
 [68.22956 ]
 [73.26445 ]
 [47.32538 ]
 [31.395884]]
10 Cost:  19.51951 
Prediction:
 [[157.21295]
 [180.22978]
 [182.36174]
 [197.56009]
 [135.7145 ]
 [ 96.56515]]
20 Cost:  18.911451 
Prediction:
 [[157.84521 ]
 [181.02458 ]
 [183.12665 ]
 [198.39592 ]
 [136.32704 ]
 [ 97.025154]]
30 Cost:  18.794117 
Prediction:
 [[157.82928]
 [181.04   ]
 [183.1238 ]
 [198.39563]
 [136.3451 ]
 [ 97.04685]]
40 Cost:  18.67766 
Prediction:
 [[157.80905]
 [181.0501 ]
 [183.11578]
 [198.3897 ]
 [136.35905]
 [ 97.06552]]
50 Cost:  18.561937 
Prediction:
 [[157.78886 ]
 [181.06015 ]
 [183.10776 ]
 [198.38376 ]
 [136.37296 ]
 [ 97.084114]]
60 Cost:  18.446949 
Prediction:
 [[157.76872]
 [181.07016]
 [183.09976]
 [198.37782]
 [136.38681]
 [ 97.10264]]
70 Cost:  18.332771 
Prediction:
 [[157.74867]
 [181.08014]
 [183.09178]
 [198.37192]
 [136.40062]
 [ 97.12109]]
80 Cost:  18.21932 
Prediction:
 [[157.72867]
 [181.09007]
 [183.08383]
 [198.36601]
 [

750 Cost:  12.096775 
Prediction:
 [[156.52986]
 [181.68695]
 [182.60822]
 [198.00967]
 [137.24353]
 [ 98.23972]]
760 Cost:  12.024362 
Prediction:
 [[156.5139 ]
 [181.69487]
 [182.6019 ]
 [198.00488]
 [137.25461]
 [ 98.25431]]
770 Cost:  11.952413 
Prediction:
 [[156.49803 ]
 [181.7028  ]
 [182.5956  ]
 [198.00012 ]
 [137.26567 ]
 [ 98.268845]]
780 Cost:  11.880954 
Prediction:
 [[156.4822 ]
 [181.7107 ]
 [182.58932]
 [197.99536]
 [137.27667]
 [ 98.28334]]
790 Cost:  11.809917 
Prediction:
 [[156.4664  ]
 [181.71857 ]
 [182.58308 ]
 [197.99063 ]
 [137.28767 ]
 [ 98.297775]]
800 Cost:  11.739404 
Prediction:
 [[156.45068 ]
 [181.72643 ]
 [182.57686 ]
 [197.98592 ]
 [137.29861 ]
 [ 98.312164]]
810 Cost:  11.669288 
Prediction:
 [[156.43498]
 [181.73424]
 [182.57065]
 [197.98119]
 [137.30952]
 [ 98.32651]]
820 Cost:  11.599687 
Prediction:
 [[156.41937]
 [181.74205]
 [182.56447]
 [197.9765 ]
 [137.3204 ]
 [ 98.3408 ]]
830 Cost:  11.530494 
Prediction:
 [[156.40378]
 [181.7498 ]
 [182.558

1490 Cost:  7.8396497 
Prediction:
 [[155.48267 ]
 [182.21025 ]
 [182.19434 ]
 [197.6921  ]
 [137.9764  ]
 [ 99.194855]]
1500 Cost:  7.795122 
Prediction:
 [[155.47023]
 [182.2165 ]
 [182.18944]
 [197.6883 ]
 [137.9852 ]
 [ 99.20618]]
1510 Cost:  7.7508903 
Prediction:
 [[155.4578  ]
 [182.22272 ]
 [182.18454 ]
 [197.68445 ]
 [137.99393 ]
 [ 99.217445]]
1520 Cost:  7.7069397 
Prediction:
 [[155.44543]
 [182.22891]
 [182.17966]
 [197.68065]
 [138.00267]
 [ 99.22868]]
1530 Cost:  7.6632657 
Prediction:
 [[155.4331 ]
 [182.2351 ]
 [182.1748 ]
 [197.67688]
 [138.01138]
 [ 99.23989]]
1540 Cost:  7.6199126 
Prediction:
 [[155.4208  ]
 [182.24124 ]
 [182.16995 ]
 [197.67307 ]
 [138.02003 ]
 [ 99.251045]]
1550 Cost:  7.5768228 
Prediction:
 [[155.40857]
 [182.2474 ]
 [182.16515]
 [197.66931]
 [138.02869]
 [ 99.26218]]
1560 Cost:  7.5340157 
Prediction:
 [[155.39636]
 [182.25352]
 [182.16032]
 [197.66556]
 [138.03731]
 [ 99.27325]]
1570 Cost:  7.4914665 
Prediction:
 [[155.38417]
 [182.2596 ]
 

In [32]:
# ask my score
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

Your score will be  [[171.51591]]


In [33]:
print("Other score will be ", sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Other score will be  [[151.81735]
 [187.5596 ]]
